Dir {
  ArchiveDir ".";
  CacheDir "/tmp/apt-ftparchive-cache";
};

Default {
  Packages::Compress ". gzip xz";
};

BinDirectory "apt/pool/main" {
  Packages "apt/dists/stable/main/binary-amd64/Packages";
  Architecture "amd64";
};

BinDirectory "apt/pool/main" {
  Packages "apt/dists/stable/main/binary-arm64/Packages";
  Architecture "arm64";
};
